### ISSUE TITLE
rect elements are forced to a square

### ISSUE THREAD

**Issue by hyblocker** [strencher-kernel/pc-compat#2]
Using the plugin [Better Status Indicators](https://github.com/griefmodz/better-status-indicators) and looking at mobile status indicators, one can notice that mobile status indicators look off.

![Broken Mobile Indicator](https://cdn.discordapp.com/attachments/859494875384512563/916684167201296414/unknown.png)

Upon further inspection, it seems that the `height` and `y` attributes of the `rect` element inside the `foreignObject` are set to the same value as the `width` and `x` attributes' values.
![DOM Showing incorrect Y components](https://cdn.discordapp.com/attachments/859494875384512563/916684167415218227/unknown.png)

This only occurs when running under pc-compat.

**Comment by slow** [comment]
Try the `dev` branch for me.

**Comment by hyblocker** [comment]
I've replicated this on the dev branch

**Comment by slow** [comment]
Fixed in 2ca19a59fc31f199572068bc66e5c3e5ec9ffbad
